name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Build artifact
        run: |
          echo "Building artifact as a binary file ..."
          make build

      - name: Create Release and Generate Notes
        uses: softprops/action-gh-release@v1
        with:
          name: idled ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            ./bin/idled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}